title: P.H. Huang
author: GitHub User
email: pohsuanh@usc.edu
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/myblog/" # the subpath of your site, e.g. /blog
url: "Po-Hsuan-Huang-github.io/myblog" # the base hostname & protocol for your site, e.g. http://example.com

website: Po-Hsuan-Huang-github.io
github_username: Po-Hsuan-Huang 
bitbucket_username:  Po-Hsuan-Huang
codepen_username: Po-Hsuan-Huang
linkedin_username: pohsuanhuang
twitter_username: Po-Hsuan-Huang
facebook_username: Po-Hsuan-Huang
instagram_username: Po-Hsuan-Huang
keybase_username: Po-Hsuan-Huang
paypal_username: Po-Hsuan-Huang
stackoverflow_username:  Vespa # (developer story)


collections:
  - setup

# disqus:
#   shortname:

# Minimaless date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minimaless:
  date_format: "%b %-d, %Y"
preview_posts: true
permalink: /:title
paginate: 10 # increase this value to reflect how many posts per page you want
paginate_path: "/page:num/"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - _pages/about.md  # short discription/ Curriculum Vitae/ Selected Honors/ Contact
  - _pages/projects.md # protfolio ( originally feature&setup  )
  - _pages/posts.md    
  - _pages/publications.md 
  - _pages/contact.md  # Address/ Map-plugin / LinkedIn/ 

  # considering merging blogs/codes/ project/ under the name research

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-archives
  - jekyll-paginate
  - jekyll-include-cache

markdown: kramdown
theme: minimaless
#remote_theme: brettinternet/minimaless # uncomment to allow GitHub to build for GitHub Pages - https://github.com/blog/2464-use-any-theme-with-github-pages

include:
  - _pages
exclude:
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - tmp
